turbine:
  aggregator:
    clusterConfig: FLIGHT-INTEGRATION-SERVICE
  appConfig: flight-integration-service
InstanceDiscovery:
  impl: com.netflix.turbine.discovery.EurekaInstanceDiscovery.class
spring:
  application:
    name: turbine
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      statusPageUrlPath: ${management.contextPath}/info
      healthCheckUrlPath: ${management.contextPath}/health